"""add chess players

Revision ID: 106e0b020783
Revises: 5f8dce9e6865
Create Date: 2023-10-30 22:58:33.567694

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "106e0b020783"
down_revision: Union[str, None] = "5f8dce9e6865"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chess_board", sa.Column("white", sa.String(), nullable=True))
    op.add_column("chess_board", sa.Column("black", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chess_board", "black")
    op.drop_column("chess_board", "white")
    # ### end Alembic commands ###
