"""init

Revision ID: 5f8dce9e6865
Revises: 
Create Date: 2023-10-30 20:40:05.272845

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f8dce9e6865"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chess_board",
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("fen", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    op.create_table(
        "user_saved_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("data", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_saved_message_channel_id"),
        "user_saved_message",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_saved_message_user_id"),
        "user_saved_message",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_saved_message_user_id"), table_name="user_saved_message"
    )
    op.drop_index(
        op.f("ix_user_saved_message_channel_id"), table_name="user_saved_message"
    )
    op.drop_table("user_saved_message")
    op.drop_table("chess_board")
    # ### end Alembic commands ###
